# Generated by Django 3.2.3 on 2021-06-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=16)),
                ('player_year', models.IntegerField(default=2020)),
                ('players_liquid_money', models.IntegerField()),
                ('players_total_money', models.IntegerField()),
                ('stock_1', models.IntegerField()),
                ('stock_2', models.IntegerField()),
                ('stock_3', models.IntegerField()),
                ('stock_4', models.IntegerField()),
                ('stock_5', models.IntegerField()),
                ('stock_6', models.IntegerField()),
                ('stock_7', models.IntegerField()),
                ('stock_8', models.IntegerField()),
                ('stock_9', models.IntegerField()),
                ('stock_10', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='player_targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('march_target', models.IntegerField()),
                ('june_target', models.IntegerField()),
                ('sept_target', models.IntegerField()),
                ('december_target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stocks_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan_value', models.IntegerField(default=0)),
                ('feb_value', models.IntegerField()),
                ('mar_value', models.IntegerField()),
                ('april_value', models.IntegerField()),
                ('may_value', models.IntegerField()),
                ('june_value', models.IntegerField()),
                ('july_value', models.IntegerField()),
                ('aug_value', models.IntegerField()),
                ('sept_value', models.IntegerField()),
                ('oct_value', models.IntegerField()),
                ('nov_value', models.IntegerField()),
                ('december_value', models.IntegerField()),
                ('stock_symbol', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='time_trackers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions_base', models.IntegerField(default=5)),
                ('current_month', models.CharField(default='January', max_length=16)),
                ('target_month', models.CharField(default='March', max_length=16)),
            ],
        ),
    ]
