# Generated by Django 3.2.3 on 2021-06-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='player_targets',
            new_name='player_target',
        ),
        migrations.RenameModel(
            old_name='time_trackers',
            new_name='time_tracker',
        ),
    ]
