# Generated by Django 3.2.3 on 2021-06-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210616_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_info',
            name='stock_1',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='stock_10',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='stock_2',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='stock_3',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='stock_4',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='stock_5',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='stock_6',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='stock_7',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='stock_8',
        ),
        migrations.RemoveField(
            model_name='player_info',
            name='stock_9',
        ),
    ]
