# Generated by Django 3.2.3 on 2021-06-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210616_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_beginning_money', models.FloatField(default=0.0)),
                ('players_liquid_money', models.FloatField(default=0.0)),
                ('players_total_money', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='player_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=16)),
                ('player_year', models.IntegerField(default=2020)),
            ],
        ),
        migrations.CreateModel(
            name='stock_identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='player_info',
        ),
        migrations.RenameField(
            model_name='time_tracker',
            old_name='actions_base',
            new_name='action_economy',
        ),
        migrations.RemoveField(
            model_name='stocks_info',
            name='stock_symbol',
        ),
        migrations.AlterField(
            model_name='player_target',
            name='december_target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player_target',
            name='june_target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player_target',
            name='march_target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player_target',
            name='sept_target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='april_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='aug_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='december_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='feb_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='jan_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='july_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='june_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='mar_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='may_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='nov_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='oct_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocks_info',
            name='sept_value',
            field=models.FloatField(default=0.0),
        ),
    ]
