# Generated by Django 3.2.3 on 2021-06-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20210616_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
