# Generated by Django 3.2.3 on 2021-06-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20210629_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_option',
            name='december_target',
            field=models.FloatField(default=200.0),
        ),
        migrations.AddField(
            model_name='player_option',
            name='june_target',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='player_option',
            name='march_target',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='player_option',
            name='players_liquid_money',
            field=models.FloatField(default=500.0),
        ),
        migrations.AddField(
            model_name='player_option',
            name='players_total_money',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name='player_option',
            name='sept_target',
            field=models.FloatField(default=150.0),
        ),
        migrations.AddField(
            model_name='stocks_info',
            name='stock_symbol',
            field=models.CharField(default='ABC', max_length=5),
        ),
    ]
