# Generated by Django 3.2.3 on 2021-06-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20210629_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_option',
            old_name='march_target',
            new_name='worth_target',
        ),
        migrations.RemoveField(
            model_name='player_option',
            name='december_target',
        ),
        migrations.RemoveField(
            model_name='player_option',
            name='june_target',
        ),
        migrations.RemoveField(
            model_name='player_option',
            name='sept_target',
        ),
    ]
