# Generated by Django 3.2.3 on 2021-06-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_auto_20210629_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks_info',
            name='amount_owned',
            field=models.IntegerField(default=3),
        ),
    ]
