# Generated by Django 3.2.3 on 2021-07-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_stocks_info_past_dec_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks_info',
            name='stock_symbol',
            field=models.CharField(default='ABC', max_length=20),
        ),
    ]
