# Generated by Django 3.2.3 on 2021-08-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_stocks_info_current_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_worth_monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worth_end', models.FloatField(default=10000.0)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(default='None', max_length=20)),
                ('amount_purchased', models.IntegerField(default=0)),
                ('purchase_method', models.CharField(default='buy', max_length=16)),
                ('when_purchased', models.CharField(default='Blank', max_length=20)),
            ],
        ),
    ]
