# Generated by Django 3.2.3 on 2021-08-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_player_worth_monthly_purchase_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_history',
            name='value_purchased',
            field=models.FloatField(default=0.0),
        ),
    ]
